rewards-key: null
rewards:
  - item: diamond
    name: default
    enchantments:
      - "Effeciency": 5
    lore: [ "" ]
  - item: diamond_sword
    name: "Legend Sword"
    enchantments: [ "" ]
    lore: [ "" ]
  - item: diamond_sword
    name: "Legend Sword"
    enchantments: [ "" ]
    lore: [ "" ]